#!/usr/bin/env python3
"""
Export pipeline outputs to a JavaScript data file for the dashboard.
Reads all JSON files from outputs/accounts/ and generates dashboard/dashboard_data.js
"""
import os
import json
import sys

def export_dashboard_data():
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    accounts_dir = os.path.join(base, "outputs", "accounts")
    output_file = os.path.join(base, "dashboard", "dashboard_data.js")

    if not os.path.isdir(accounts_dir):
        print(f"❌ No accounts directory found at {accounts_dir}")
        sys.exit(1)

    data = {}
    account_dirs = sorted(os.listdir(accounts_dir))

    for account_id in account_dirs:
        account_path = os.path.join(accounts_dir, account_id)
        if not os.path.isdir(account_path):
            continue

        data[account_id] = {}

        for version in ["v1", "v2"]:
            version_path = os.path.join(account_path, version)
            if not os.path.isdir(version_path):
                continue

            data[account_id][version] = {}

            for filename in sorted(os.listdir(version_path)):
                if filename.endswith(".json"):
                    filepath = os.path.join(version_path, filename)
                    try:
                        with open(filepath, "r", encoding="utf-8") as f:
                            file_data = json.load(f)
                        data[account_id][version][filename] = file_data
                        print(f"  ✅ Loaded {account_id}/{version}/{filename}")
                    except Exception as e:
                        print(f"  ❌ Error loading {filepath}: {e}")

    # Write JS file
    js_content = f"// Auto-generated by export_dashboard_data.py\n"
    js_content += f"// Generated at: {__import__('datetime').datetime.now().isoformat()}\n"
    js_content += f"const PIPELINE_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};\n"

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(js_content)

    total_accounts = len(data)
    v1_count = sum(1 for a in data.values() if "v1" in a)
    v2_count = sum(1 for a in data.values() if "v2" in a)

    print(f"\n📊 Exported {total_accounts} accounts ({v1_count} v1, {v2_count} v2)")
    print(f"💾 Saved to: {output_file}")


if __name__ == "__main__":
    export_dashboard_data()
